### ISSUE TITLE
标签\分享按钮无法获取并跳转到正确的Memos链接。

### ISSUE THREAD

**Issue by lniaen** [lmm214/memobbs#23]
BLOG: [https://www.lniaen.com](url)
BLOG Memos页: [](https://www.lniaen.com/index.php/memos.html)
Memos: [https://memos.lniaen.com](url)

在元素检查中，标签按钮指向的是
` onclick="getTagNow('undefined','1','lniaen','undefined',this)" `

分享按钮指向的是
` href="undefined/m/FuDmd7Be7JJ67bnsBUAoCr" `

当我点击分享按钮则会跳转至 https://www.lniaen.com/index.php/undefined/m/FuDmd7Be7JJ67bnsBUAoCr，并返回404错误。

当点击标签按钮时则会出现内容处为空白

```
GET https://www.lniaen.com/index.php/undefined/api/v1/memo?creatorId=1&tag=%E6%84%9F%E6%83%B3&rowStatus=NORMAL&limit=50 404 (Not Found)
Error
    at getUserMemos (memos.js:1212:19)
```

貌似脚本没有正确的${link}变量？亦或者是typecho博客重定向的问题？

**我尝试测试过了他人的memos链接，结果则是一切正常……**

还请林老师不吝赐教，万分感谢！

**Comment by lmm214** [comment]
可能是 memos.lniaen.com后面多了斜杠 /
或者是昵称和 Memos 站点不匹配
