### ISSUE TITLE
什么时候支持v0.22版本呢？

### ISSUE THREAD

**Issue by yaoleistable** [lmm214/memobbs#31]
现有数据是0.22版本的，不知道怎么降级到0.18，请问啥时候可以支持下0.22版本？

**Comment by xu4wang** [comment]
请问下 0.22 是需要 V2 版本的API吗？  @lmm214 

我在用的一个memos logseq sync工具也碰到API不兼容的问题了。 想看下如何解决。 https://github.com/xu4wang/logseq-memos-sync/issues/1

**Comment by lmm214** [comment]
暂无支持计划，主要0.22.1又回到v1接口了，而且由跨域报错，无解。
