### ISSUE TITLE
我问下，适配pjax吗

### ISSUE THREAD

**Issue by SinzMise** [lmm214/memobbs#35]
这边说一下问题：因为我站点是默认开启pjax的（我站点的很多js都得用到pjax）
但是开了pjax之后跳转到bbs会出现没法加载或者加载不完全的原因
我想问这个是不是pjax的问题？还是是我站点的问题
如果是我站点的问题的话大佬能说下是什么原因吗？
页面在这：https://blog.sinzmise.top/bbs2/
（要点进去的话得在‘友链’里面的哔哔广场pjax那个，哔哔广场的这个是iframe的）

**Comment by D-Bood** [comment]
应该不支持pjax
不过我觉得可以参考[MetingJS](https://github.com/metowolf/MetingJS)，用customElements改一下
